blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Dokumentation
    url: https://docs.webgiscloud.com/de/webgis/index.html
    about: Bitte zuerst in der Dokumentation nachsehen (viele Fragen sind dort bereits beantwortet).

  - name: ðŸ’¬ Community Discussions (Fragen, How-to, Ideen)
    url: https://github.com/e-netze/webgis-community/discussions
    about: FÃ¼r allgemeine Fragen, How-tos und Diskussionen. FÃ¼r konkrete Bugs/Features/Fragen bitte Issues verwenden.
